# Site settings
title: OS X Sync
email: agassi21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Mac-sync" # the subpath of your site, e.g. /blog/
url: "http://agassiyzh.github.io" # the base hostname & protocol for your site
twitter_username: agassi_yzh
github_username:  agassiyzh

# Build settings
sass:
  sass_dir: _sass
  style: :compressed

# limit_posts: 5
paginate: 5
page_path: "page:num"
# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: /:title/index.html

timezone: Asia/Shanghai
